### ISSUE TITLE
Junit test: ITest.timestamp_input_is_tolerant_of_various_formats_in_all_locales

### ISSUE THREAD

**Issue by JuKu** [awkay/easy-i18n#11]
I have debugged a little bit this JUnit test and i think the problem is the missing "a" in the SimpleDateFormat pattern, a stands for am/pm, see here:
https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

Maybe this is also the problem in the others tests, the "a" was never considered.

**Comment by JuKu** [comment]
I have debugged a little bit more, the problem is in `LanguageSetting.getLongTimeFormat()`, there the "a" is missing.
But i dont know much about, what method `getLongTimeFormat()` do.
```java
public DateFormat getLongTimeFormat() {
    return (SimpleDateFormat) DateFormat.getTimeInstance(DateFormat.MEDIUM);
  }
```

Maybe here is the problem oft most of the failing JUnit tests?

**Comment by JuKu** [comment]
For debugging i have changed the method a little bit, so that a Exception is thrown, if no pattern fit for the time string:
```java
public static Date stringToTime(Date refDate, String timeString) {
    if (isNullDate(refDate)) {
      if (defaultDate == null)
        refDate = new Date();
      else
        refDate = defaultDate;
    }
    Date timeDate = new Date(0, 0, 0, 0, 0, 0);

    LanguageSetting s = languageProvider.vend();
    for (DateFormat fmt : new DateFormat[] { s.getLongTimeFormat(), s.getShortTimeFormat(),
                                             s.getMilitaryTimeFormat(true), s.getMilitaryTimeFormat(false),
                                             s.getAccurateTimeFormat(), s.getCompactMilitaryTimeFormat()}) {
      boolean found = false;

      try {
        timeDate = fmt.parse(timeString);
        found = true;
        break;
      } catch (ParseException e) {
      }

      if (!found) {
        for (DateFormat fmt1 : new DateFormat[] { s.getLongTimeFormat(), s.getShortTimeFormat(),
                s.getMilitaryTimeFormat(true), s.getMilitaryTimeFormat(false),
                s.getAccurateTimeFormat(), s.getCompactMilitaryTimeFormat() }) {
          System.err.println(((SimpleDateFormat) fmt1).toLocalizedPattern());
        }


        throw new IllegalStateException("No pattern found for time string: " + timeString);
      }
    }

    return new Date(refDate.getYear(), refDate.getMonth(), refDate.getDate(), timeDate.getHours(),
                    timeDate.getMinutes(), timeDate.getSeconds());
  }
```

The output on the test is:
```
HH:mm:ss
HH:mm
H:m:s
H:m
H:m:s.S
HHmm

java.lang.IllegalStateException: No pattern found for time string: 11:37 PM

	at com.teamunify.i18n.I.stringToTime(I.java:712)
	at com.teamunify.i18n.I.stringToTimestamp(I.java:664)
	at com.teamunify.i18n.ITests.timestamp_input_is_tolerant_of_various_formats_in_all_locales(ITests.java:832)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

So this means there is not pattern to handle am / pm times, yet.

**Comment by awkay** [comment]
So, I appreciate the work, but I don't have time to maintain this, which is why the new maintainer issue is open.  If you want to take over (on your fork), and deploy it via maven, then I'd be glad to redirect the README to your fork.
